CREATE TABLE [dbo].[Mensagens] 
(
  idMsg INTEGER entit NOT NULL AUTO_INCREMENT,
  descricaoMsg VARCHAR NULL,
  BLOCO INTEGER UNSIGNED NULL,
  APARTAMENTO INTEGER UNSIGNED NULL,
  datavigenciaMsg DATE NULL,
  statusMsg CHAR NULL,
  PRIMARY KEY(idMensagens)
)