/****** Object:  ForeignKey [FK_AGENDA_APARTAMENTO]    Script Date: 12/10/2012 11:26:47 ******/
ALTER TABLE [dbo].[AGENDA]  WITH CHECK ADD  CONSTRAINT [FK_AGENDA_APARTAMENTO] FOREIGN KEY([PROPRIETARIO_BLOCO], [PROPRIETARIO_AP])
REFERENCES [dbo].[APARTAMENTO] ([BLOCO], [APARTAMENTO])


GO
ALTER TABLE [dbo].[AGENDA] CHECK CONSTRAINT [FK_AGENDA_APARTAMENTO]

