/****** Object:  ForeignKey [FK_LANCAMENTO_OCORRENCIA_OCORRENCIA]    Script Date: 12/10/2012 11:26:47 ******/
ALTER TABLE [dbo].[LANCAMENTO_OCORRENCIA]  WITH CHECK ADD  CONSTRAINT [FK_LANCAMENTO_OCORRENCIA_OCORRENCIA] FOREIGN KEY([CODIGO_OCORRENCIA])
REFERENCES [dbo].[OCORRENCIA] ([CODIGO])


GO
ALTER TABLE [dbo].[LANCAMENTO_OCORRENCIA] CHECK CONSTRAINT [FK_LANCAMENTO_OCORRENCIA_OCORRENCIA]

