/****** Object:  ForeignKey [FK_MENSAGEM_MORADOR_PROPRIETARIO]    Script Date: 12/10/2012 11:26:47 ******/
ALTER TABLE [dbo].[MENSAGEM_MORADOR]  WITH CHECK ADD  CONSTRAINT [FK_MENSAGEM_MORADOR_PROPRIETARIO] FOREIGN KEY([BLOCO], [APARTAMENTO])
REFERENCES [dbo].[PROPRIETARIO] ([PROPRIETARIO_BLOCO], [PROPRIETARIO_AP])


GO
ALTER TABLE [dbo].[MENSAGEM_MORADOR] CHECK CONSTRAINT [FK_MENSAGEM_MORADOR_PROPRIETARIO]

