/****** Object:  ForeignKey [FK_OCORRENCIA_APARTAMENTO]    Script Date: 12/10/2012 11:26:47 ******/
ALTER TABLE [dbo].[LANCAMENTO_OCORRENCIA]  WITH CHECK ADD  CONSTRAINT [FK_OCORRENCIA_APARTAMENTO] FOREIGN KEY([BLOCO], [AP])
REFERENCES [dbo].[APARTAMENTO] ([BLOCO], [APARTAMENTO])


GO
ALTER TABLE [dbo].[LANCAMENTO_OCORRENCIA] CHECK CONSTRAINT [FK_OCORRENCIA_APARTAMENTO]

