/****** Object:  ForeignKey [FK_PROPRIETARIO_APARTAMENTO]    Script Date: 12/10/2012 11:26:47 ******/
ALTER TABLE [dbo].[PROPRIETARIO]  WITH CHECK ADD  CONSTRAINT [FK_PROPRIETARIO_APARTAMENTO] FOREIGN KEY([PROPRIETARIO_BLOCO], [PROPRIETARIO_AP])
REFERENCES [dbo].[APARTAMENTO] ([BLOCO], [APARTAMENTO])


GO
ALTER TABLE [dbo].[PROPRIETARIO] CHECK CONSTRAINT [FK_PROPRIETARIO_APARTAMENTO]

